'use strict';
const fullName = 'Joe Park';
console.log('variable fullName: ', fullName);
console.log('Type of variable fullName: ', typeof fullName);
const isCool = true;
console.log('type of variable isCool', typeof isCool);
const totalPets = 1;
console.log('type of variable totallPets: ', typeof totalPets);
const empty = null;
console.log('empty variable: ', empty);
console.log('type of variable empty: ', typeof empty);
let nothing;
console.log('nothing variable: ', nothing);
console.log('type of nothing variable: ', typeof nothing);
