'use strict';
const width = 5;
const height = 8;
const area = width * height;
console.log('Area: ', area);
console.log('type of area: ', area);
const bill = 2;
const payment = 5;
const change = payment - bill;
console.log('Change: ', change);
console.log('Type of change: ', typeof change);
const quizzes = 70;
const midterm = 80;
const final = 100;
const grade = (quizzes + midterm + final) / 3;
console.log('Grade: ', grade);
console.log('type of Grade: ', typeof grade);
const firstName = 'Joe';
const lastName = 'Park';
const fullName = firstName + ' ' + lastName;
console.log('Full name: ', fullName);
console.log('Type of Full Name: ', typeof fullName);
const pH = 5;
const isAcidic = pH < 7;
console.log('isAcidic value: ', isAcidic);
console.log('Type of isAcidic variable: ', typeof isAcidic);
const headCount = 250;
const isSparta = headCount === 300;
console.log('is this Sparta?', isSparta);
console.log('Type of isSparta: ', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('motto: ', motto);
console.log('type of motto: ', typeof motto);
